version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=${DEV_DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - filmjunkiez-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@filmjuniez.com
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5555:80"
    networks:
      - filmjunkiez-network
  django:
    build: .
    user: myuser
    volumes:
      - .:/app
    working_dir: /FilmJunkiez/filmjunkiez
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - filmjunkiez-network
    environment:
      - PORT=${PORT}
      - DJANGO_DB_NAME=${DATABASE_NAME}
      - DJANGO_DB_USER=${DATABASE_USER}
      - DJANGO_DB_PASSWORD=${DATABASE_PASSWORD}
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=${DEV_DB_PORT}
      - DOCKERIZED=1 
    
networks:
  filmjunkiez-network:
    driver: bridge

volumes:
  postgres_data:
